version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - "MYSQL_DATABASE=newDatabase3"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD="
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "127.0.0.1:3307:3306"

  app:
    image: 'user-management:latest'
    container_name: user-management
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/newDatabase3?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    ports:
      - "127.0.0.1:8080:8080"