package com.example.wholeProject.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor

public class AuthToken {
    @ApiModelProperty(value = "the token generated by the system")
    private String token;

    @ApiModelProperty(value = "the username of the user")
    private String username;
}
